-- ====================================================================
-- SUPABASE DIRECT BACKEND SCHEMA
-- Electricity Bill Monitoring & Reminder System
-- Run this script in your Supabase Dashboard: SQL Editor -> New Query -> Run
-- ====================================================================

-- 1. Create PROFILES Table (stores user settings & profile details)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    alternate_phone TEXT,
    sms_reminders BOOLEAN DEFAULT TRUE,
    email_reminders BOOLEAN DEFAULT TRUE,
    whatsapp_reminders BOOLEAN DEFAULT TRUE,
    phone_reminders BOOLEAN DEFAULT TRUE,
    sms_recipient_phone TEXT,
    email_recipient_email TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT 
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- 2. Create METERS Table (Electricity connections)
CREATE TABLE IF NOT EXISTS public.meters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    service_number TEXT NOT NULL,
    board_name TEXT NOT NULL,
    consumer_name TEXT NOT NULL,
    address TEXT NOT NULL,
    prediction_reminder_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.meters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own meters" 
ON public.meters FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own meters" 
ON public.meters FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own meters" 
ON public.meters FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own meters" 
ON public.meters FOR DELETE 
USING (auth.uid() = user_id);

-- 3. Create BILLS Table
CREATE TABLE IF NOT EXISTS public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    meter_id BIGINT REFERENCES public.meters(id) ON DELETE SET NULL,
    bill_no TEXT NOT NULL,
    service_no TEXT NOT NULL,
    month TEXT NOT NULL,
    units NUMERIC DEFAULT 0,
    amount NUMERIC NOT NULL,
    due_date TEXT NOT NULL,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own bills" 
ON public.bills FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bills" 
ON public.bills FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bills" 
ON public.bills FOR UPDATE 
USING (auth.uid() = user_id);

-- 4. Create REMINDERS Table
CREATE TABLE IF NOT EXISTS public.reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    days_before INT NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own reminders" 
ON public.reminders FOR ALL 
USING (auth.uid() = user_id);

-- 5. Create NOTIFICATIONS Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info',
    action_url TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own notifications" 
ON public.notifications FOR ALL 
USING (auth.uid() = user_id);

-- 6. Automatically create profile on User Sign Up (Trigger)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, phone)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', 'Consumer User'),
    new.email,
    COALESCE(new.raw_user_meta_data->>'phone', '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
